### PR TITLE
Issue #93: simple workaround for infeasibility of Monte Carlo

### PR DESCRIPTION
**Pull request by jkaardal**
These changes were motivated by issue #93 where it was found that the random samples used to initialize the acquisition function maximization under constraints may struggle to find feasible points in some cases. 

Simple changes are made to allow users to instead define their own sampling function for the continuous variables:
 
  1. A new class variable, `cont_sampler`, is introduced in `GPyOpt.methods.bayesian_optimization.BayesianOptimization` which is set through `**kwargs`. `cont_sampler` is a function of two variables that returns samples of `x`. By default, `cont_sampler = None`. 
  2. `cont_sampler` is then passed in during the initialization of `GPyOpt.optimization.acquisition_optimizer.AcquisitionOptimizer` where, if there are continuous variables, `cont_sampler` is then passed through `**kwargs` to the initialization of `GPyOpt.optimization.acquisition_optimizer.ContAcqOptimizer` where the member variable `sampler` is assigned to `cont_sampler` (or `None`, if the key does not exist). 
  3. When `GPyOpt.optimization.acquisition_optimizer.ContAcqOptimizer.generate_initial_points()` is called, if `sampler == None` then the samples are initialized as in the past; otherwise, the customized sampling is computed by calling `self.sampler(self.free_bounds, self.n_samples)`. 
  4. One last change was adding `**kwargs` to `__init__` in the Opt functions of `GPyOpt.optimization.optimizer` to transmit the `**kwargs` (there are key errors otherwise).

These changes did not create any new errors from running the unit tests (and worked on my topical application where a sampler was necessary). Although, at least on the two computers I tried, the devel branch (_without_ the above changes) does not pass the unit tests with 1 error and 5 fails (which are the same after my changes).

In issue #93, there was discussion of taking an automatic approach to finding a feasible initialization. I ended up turning against this because it is not generally possible to guarantee convergence to a feasible point for any given set of nonlinear constraints (at least not in a timely manner). More related to this is brought up in a reply in the discussion of the issue.

Conflicts:
	GPyOpt/methods/bayesian_optimization.py
	GPyOpt/optimization/acquisition_optimizer.py

### CODE REVIEW

**Comment by javiergonzalezh** [comment]
HI @jkaardal,

As you may have noticed, we have refactored a large part of the code un our release last week. Do you think it would be possible to merge your changes there and send another PR?

Sorry about this and thanks so much for your contributions!

Javier

**Comment by jkaardal** [comment]
Hi @javiergonzalezh. It looks like merging the changes shouldn't be too much trouble. I will likely work on making these changes this week or over the weekend. Thanks for the notification!

**Comment by javiergonzalezh** [comment]
That's great! Just let us know when you are ready for the merge then.

**Comment by jkaardal** [comment]
An updated version of the pull request is here: https://github.com/SheffieldML/GPyOpt/pull/123.

**Pull request closed without merging**
