### PR TITLE
Issue 324 precomputed search space

### PR DESCRIPTION
**Pull request by pavel-rev**
this is a new feature for issue-324 - option to pass pre-computed search space in case it is available.

### CODE REVIEW

**Comment by apaleyes** [comment]
Just tagging mentioned issue #324

**Review by apaleyes — COMMENTED** [review]
Thanks for the contribution! Unfortunately this approach of adding optional parameters and suffixes to method names doesn't scale very well. May I suggest a slightly different approach?

As @ekalosak mentioned in the original issue, you are effectively looking to create a separate instance of what we call "experimental design". In that case the best way forward would be just define just that. Something along these lines:

```
class PrecomputedSpaceDesign(ExperimentDesign):
    def __init__(self, space, whatever_else_is_needed):
    ....
    def get_samples(self, init_point_count):
        # you whole implementation of `get_samples_with_constraints_and_all_x_values` goes in here
```

The best thing about this approach is that it requires no changes to existing exp design classes, which helps a lot with maintenance and readability of the code in a long run.

**Comment by pavel-rev** [comment]
ok, let me explore this path then.

**Comment by pavel-rev** [comment]
ok, I accidentally closed this PR, and as I recreated branch, I cannot reopen, I have to do another PR.

**Pull request closed without merging**
