### PR TITLE
Update notebook related to GPyOpt-sklearn interface.

### PR DESCRIPTION
**Pull request by fdtomasi**
Added a classification example on some synthetic data.
Divided the notebook into two sections, "Regression" and "Classification".

### CODE REVIEW

**Comment by javiergonzalezh** [comment]
Hi @fdtomasi,

Instead of merging your PR, we have directly included your notebook in our last release. Could you check that it is OK so we can close this PR?

Thanks for your contribution!

Javier

**Comment by javiergonzalezh** [comment]
The notebook is here, btw,
https://github.com/SheffieldML/GPyOpt/blob/master/manual/GPyOpt_scikitlearn.ipynb

you should add your name to it! :)

Javier

**Comment by fdtomasi** [comment]
Perfect, thank you! :+1:

**Comment by javiergonzalezh** [comment]
Great, I close this notebook then. Thanks for contributing!

**Pull request closed without merging**
