### PR TITLE
Implementing Probability of Feasibility (PoF) constraint handling - w/ corrections

### PR DESCRIPTION
**Pull request by jhelsas**
Dear Mr. Paleyes and GPyOpt authors,

         As I did in PR # 239 (https://github.com/SheffieldML/GPyOpt/pull/239), I would like to upstream some additions I made to your code to enable GPyOpt to handle black box constraints of the type g_k(x) >= 0.
        Since the last message I have modified GPyOpt acquisition and method classes to enable them to handle blackbox constraints with minor modifications, and without code duplication.
        I hope it is now compliant with the policies necessary to integrate with your codebase. Is any additional changes are necessary to accept the pull request, please let me know.

Best regards,

José Hugo Elsas

### CODE REVIEW

**Comment by abyvinod** [comment]
Hi, this is exactly the feature I have been looking for. Can I start using the code in this pull request? Are the tests the reason why this pull request is left unmerged, or are there any other bugs/issues left to be resolved in the code?

**Comment by jhelsas** [comment]
Dear Abraham,
     I didn't managed to merge with trunk at the time, and I became busy afterwards. I didn't try to reach them since. I think there are still some conformity problems regarding position of arguments on the function calls to be solved.
     That said, I have been working continuously with GPyOpt with PoF without problems for more than a year now, I can help you download my branch and check if it is working with your problem if you wish.

**Comment by abyvinod** [comment]
@jhelsas Thank you for the offer. I was able to use https://github.com/amzn/emukit for implementing constrained EI.

**Comment by cmleecm** [comment]
@abyvinod What does your constrained EI look like? I am asking because my constraint is a function f(x_1, x_2, ...., x_n), potentially doing some complicated stuff and could even be a black box itself. The current way of specifying the constraint explicitly on the variables x_1, ..., x_n doesn't quite work for me. Is there anyway to pass the constraint as a function?

**Comment by abyvinod** [comment]
My constraint was an explicit function of the decision variables. However, emukit also permits a sequential approach that provides the next "best" query point.
https://github.com/amzn/emukit/blob/645eb88c07e4f3ec3fc6e7ff16e1428f4846720c/integration_tests/emukit/bayesian_optimization/test_unknown_constraints_bayesian_optimization.py

**Comment by sbatururimi** [comment]
Hi, @jhelsas . I would like to use your implementation. Is there any example that could help with that? Thank you.

**Comment by apaleyes** [comment]
Closing as we have declared end of maintenance.

**Pull request closed without merging**
