### PR TITLE
Remove python 2 support and bump the version

### PR DESCRIPTION
**Pull request by zhenwendai**
- Drop the Python 2 support as GPy no longer supports Python 2.
- Bump the version.

### CODE REVIEW

**Comment by zhenwendai** [comment]
The version that we officially drop Python 2.7 support will be 1.9.10 (To be released to PyPi soon).

**Comment by ekalosak** [comment]
It might be good to add the Python2 support notes from this PR into the FAQ.

**Comment by apaleyes** [comment]
@zhenwendai if you don't mind let's hold off merging this until GPy version is available. We can make sure reqs are updated as well then.

**Comment by zhenwendai** [comment]
Sure. Let's wait for GPy. GPy will release a new version before GPSS for sure, so it will not take too long.

**Comment by apaleyes** [comment]
Closing as we have declared end of maintenance.

**Pull request closed without merging**
