### PR TITLE
[MRG] Python 3 compatibility

### PR DESCRIPTION
**Pull request by glouppe**
This a work in progress towards making GPyOpt Python 3 compatible

* [x] Make GPyOpt at least importable from Python 3
* [x] Make sure all tests still pass... 
* [x] ... and fix incompatible constructs

By the way, I realize there is no continuous integration? Is this something on its way? (That would have been handy to make sure these changes dont break everything)

CC: @mikecroucher

### CODE REVIEW

**Comment by mikecroucher** [comment]
@glouppe Yes, CI etc is all on the way. I recently won some funding to be able to spend time to work on this project. I'll be starting on it in anger very soon.

@javiergonzalezh I have permissions to merge pull requests to master. Are you happy for me to do so with this one?

**Comment by mikecroucher** [comment]
@glouppe I'm not going to be able to look at this today though. Need to attend to some RT stuff. If there's anything left to do next week I'll take another look. Thanks for contributing :)

**Comment by glouppe** [comment]
> @javiergonzalezh I have permissions to merge pull requests to master. Are you happy for me to do so with this one?

Please dont merge yet, this is still a work in progress :)

**Comment by javiergonzalezh** [comment]
@mikecroucher, totally fine with me if you merge the pull requests!

**Comment by mikecroucher** [comment]
@glouppe I won't. I just wanted to make sure @javiergonzalezh was happy for me to do so when the time came.

**Comment by glouppe** [comment]
Demos and tests are now runnable under Python 3. Some are failing, but I get the same failures under Python 2.7, so I guess this is more or less fine.

**Comment by glouppe** [comment]
Ready to go on my side! Feel free to review once you have some time @mikecroucher

**Pull request closed without merging**
