### PR TITLE
Test functions

### PR DESCRIPTION
**Pull request by RJTK**
I found a couple of bugs in the example functions, I've here added tests for all of them.  I also removed the convention that the functions returned column vectors, and they now return regular 1d arrays.  I didn't see reason why they should be returning column vectors, but if this is actually important I can easily change it back.

I have also made a bit of a mistake with this request, being rather inexperienced with git, it is dependent on my other PR (#118).  Is this a big problem?  I can probably figure out how to fix, but would prefer avoiding the extra hassle.

### CODE REVIEW

**Comment by javiergonzalezh** [comment]
Hi @RJTK,

Thanks so much for your PRs! It seems that the tests are not passing with you current changes. Could you investigate before we can merge? Please let us know if you think that there is any issue with the code.

Thanks!

Javier

**Comment by RJTK** [comment]
Yeah I'm looking into the problems, I didn't realize these functions were being used in so many of the tests.  Although I definitely found some bugs with the experiment2d.py functions, so it may actually be some of the tests that are wrong.

Many of the test functions were returning `-fval` instead of just `fval`, why was that?  I switched some of them around so that all the example functions were convex-ish, rather than before where many were concave-ish.

**Comment by javiergonzalezh** [comment]
The change in the sign is because by default we minimize and some of the test functions are from a maximization benchmark. I would be great if you could adapt the changes up to a point in which all the test pass so we merge with guarantees. 

Thanks for your contributions!

**Comment by RJTK** [comment]
I will likely work on this PR again over the weekend, but are you able to address #118 first, since it is simpler?  I've never submit any PRs before so I'd like to have one finished before continuing.

**Comment by apaleyes** [comment]
Hey. I have reviewed #118 , let's focus on that one and get back here later, once the other one is finished.

Alternatively you can decouple the two, and then we can review them in parallel

**Comment by apaleyes** [comment]
As in #118 , closing this as we haven't heard from @RJTK for a while.

**Pull request closed without merging**
